### ISSUE TITLE
Card: Magic Archer

### ISSUE THREAD

**Issue by AmirSavand** [martincarrera/clash-royale-api#100]
Can't find it here: http://www.clashapi.xyz/api/cards/

**Comment by TorzuoliH** [comment]
Hello @AmirSavand, API data will be updated soon ([PR](https://github.com/martincarrera/clash-royale-api-data-generator/pull/16)).

@martincarrera

**Comment by AmirSavand** [comment]
@TorzuoliH Nice, how did I miss it haha. Make sure it resolves this issue.

**Comment by AmirSavand** [comment]
Nice

**Comment by AmirSavand** [comment]
@martincarrera @TorzuoliH the card is still not in the API.

**Comment by martincarrera** [comment]
Added.
