### ISSUE TITLE
Error 500 Internal Server Error

### ISSUE THREAD

**Issue by AmirSavand** [martincarrera/clash-royale-api#102]
What's with the error? I got em recently from cards and random API.

**Comment by AmirSavand** [comment]
Random deck works now, but cars still no...

**Comment by AmirSavand** [comment]
The problem was on my side, had the wrong API but it's so weird cuz it happened suddenly...

**Comment by AmirSavand** [comment]
Anyway, I think there should be a 404 error not 500 :wink: \

**Comment by martincarrera** [comment]
I have no idea what you did to get that error, so I am not sure what it should be 😜

**Comment by AmirSavand** [comment]
@martincarrera it was a wrong URL, so basically it should be 404 not 500 which means your server had an error processing the request.

It's easy to fix it, just check to see if the request URL is valid, else return 404 response.

**Comment by AmirSavand** [comment]
I don't know what framework you're using exactly, but in most frameworks, 404 is handled automatically.

**Comment by martincarrera** [comment]
Oh, you are right.
