### ISSUE TITLE
Proposal to lower the load and improve stability

### ISSUE THREAD

**Issue by Tithanium** [martincarrera/clash-royale-api#107]
I suspect the server load of the API does not requires all the time : 
1) specific player tag data (it can be random, as in my case...)
2) real time scavenging.

So, maybe adding an endpoint like " send me the player battle data from the 1000 last recent requests ", 
or give me n random tag battle data, it would send back only data stored into a local dB. 
This would save a lot of CPU time, wouldn't it ?

Could it help to stabilize the API (you did a great job by the way) ?

**Comment by martincarrera** [comment]
Hi!

This API does not search players and does not scavenge any data from the real game data. It just provides static information for other devs to build apps and not need to hard-code all the static data.

I'm aware that there are other APIs that do that, but I don't know if those are open source or free.

Thanks for your comments!

I'm closing this issue.
