### ISSUE TITLE
not an actual api for clash royale

### ISSUE THREAD

**Issue by Jimbolino** [martincarrera/clash-royale-api#111]
Somewhere in the readme it should be mentioned that this is not an actual api for clash royale.
I just spent 30 mins installing this, but only just found out that it does not connect to the clash royale servers.

There are a few mentions in the closed tickets, but a more obvious message in the readme would be nice.

**Comment by AmirSavand** [comment]
30 minutes for installation?

Anyway this issue is invalid, read this:

>This content is not affiliated with, endorsed, sponsored, or specifically approved by Supercell and Supercell is not responsible for it. For more information see Supercell’s Fan Content Policy.

**Comment by Jimbolino** [comment]
30 minutes was because this was my first node+mongo installation. After figuring out how to install those two, the installation was as easy as described in the readme.

I didn't mean to disrespect your project, its a great api for a lot of purposes.
Its just that the name, and readme never mention that it doesn't pull live data from the game.

The disclaimer is just a legal copy/paste that absolves supercell's responsibility.
Projects that connect to the actual supercell servers also carry this statement. For example at the bottom of https://royaleapi.com/. Since there is no official api, they have probably reverse engineered the protocol of the app, and are using that to power their website.

A lot of developers, including me, have been looking on github for a project that connects to the actual servers, but haven't found any.
https://github.com/martincarrera/clash-royale-api/issues/80
https://github.com/martincarrera/clash-royale-api/issues/39
https://github.com/martincarrera/clash-royale-api/issues/38
https://github.com/martincarrera/clash-royale-api/issues/37
https://github.com/martincarrera/clash-royale-api/issues/30

Just a small message like this in the readme would prevent some confusion: This api doesn't pull live data from the supercell servers, therefor it cannot provide live player statistics, or live clan information.

**Comment by AmirSavand** [comment]
Then we'll wait for @martincarrera @MaherFa

**Comment by jonathanlaf** [comment]
I'm facing the exact same problem. The only diff, I tried the endpoint before installing. Lost only 5 minutes. but it could be important to mention it. I found this API helpful for a lot of things, except the one I came here for.

**Comment by martincarrera** [comment]
Hey! this IS a clash royale API. It is an API and it is about clash royale.

The problem is that this only serve static information and you need live information, I'm sorry that it took 30 minutes for you to install the API and get it running locally and then realize that it was not useful for your needs.

**Comment by Jimbolino** [comment]
I didn't mean it's not a clash royale api. I meant that it doesn't pull live data from the clash royale servers.
A small message in the readme that explains this difference would be nice.

**Comment by AmirSavand** [comment]
You said that:
> this is not an actual api for clash royale.

Anyway, I think there's no point in discussing this issue as @martincarrera labeled it *wontfix*.

You could try making a pull for this but again, I don't think it's worth it.

**Comment by jonathanlaf** [comment]
I think @Jimbolino just don't have the right words, but the problem still exact. With the name being Clash Royale API, it can lead to the thinking that it serve live data. Just a little note could help ppl understanding the type of project this is all about. 

I do understand that the way it was told "This is not a clash royale api" it can be frustrating, but the message is clear.... the OP feel like someone lies to him. So there's a need for clarification.

**Comment by AmirSavand** [comment]
Maybe a note about not providing live data can help few people.

But when I searched about Clash Royale API and found this project, after looking at the endpoints, I realized this is not a live data API.

**Comment by jonathanlaf** [comment]
@AmirSavand i'm with you on that, As I said, I tested the endpoint and realized fast that it was not live data, but there's a lot of hobbyist around who will not test and check, they just assume it do what they need because it exists online ;)
