### ISSUE TITLE
Clan Information 

### ISSUE THREAD

**Issue by HeitorIshihara** [martincarrera/clash-royale-api#114]
Is there a way to get clan informations?

**Comment by HZooly** [comment]
@HeitorIshihara Clash Royale API doesn't provide real time data, you can't get clan informations. Maybe prefer [Royale API](https://github.com/RoyaleAPI/cr-api) for this kind of usage.

**Comment by AmirSavand** [comment]
If there was a way, the endpoint for getting clan information would be included in the README API section.

**Comment by HeitorIshihara** [comment]
@HZooly Thank you. I was trying to look for something like this but I wasn't successful.

**Comment by HZooly** [comment]
This is the only public API I know for this need.
