### ISSUE TITLE
Can you add my app to read me please.

### ISSUE THREAD

**Issue by Redman1037** [martincarrera/clash-royale-api#115]
Hi Bro ,
      Thanks for the API , I am using it in my app for random deck generator , can you please add it on your read me  list .
Thanks.

App name : ClashElite
PlayStore Url : https://play.google.com/store/apps/details?id=com.wordpress.redmanandroid.clashelite

**Comment by HZooly** [comment]
Hi @Redman1037,

Don't hesitate to do a pull request on this project.

**Comment by Redman1037** [comment]
Done created PR

**Comment by martincarrera** [comment]
Added! Thanks!
