### ISSUE TITLE
 how to use?

### ISSUE THREAD

**Issue by ronnyrolim** [martincarrera/clash-royale-api#13]
please give me more information on how to use this tool .

what language is that? javascript?

I have a website clash royale and would like to use

**Comment by martincarrera** [comment]
It´s currently under development, as soon as I finish with it I will upload docs explaining how to use it correctly.

It´s written in nodejs, and it´s a REST API so you can get all the information relative to Clash Royale.

I will close this issue, please check in the next couple of days for news and explanation on how to use.

Thanks!
