### ISSUE TITLE
cards details information need.

### ISSUE THREAD

**Issue by chanyap92** [martincarrera/clash-royale-api#19]
just found this good api but now it is only contain super basic information.
if card details information is provided then i will be start developing a webapp with this api.
for example pass in card id to get detail information of the card in a list by card level

**Comment by martincarrera** [comment]
Hi!

I've just released the v1 of the API with really basic information 2 days ago.

I'm working in the next version with all the card's information and some useful new features.

Please feel free to start developing your webapp and check in the next couple of days for updates.
