### ISSUE TITLE
Release on npm

### ISSUE THREAD

**Issue by keimlink** [martincarrera/clash-royale-api#24]
Thanks for the great project! 👍 Can you please release it on npm? This would make the installation a lot easier. Thanks in advance!

**Comment by martincarrera** [comment]
I'm sorry but the idea of the API is just to consume the endpoints with the data and not to host it.

If you want to submit a PR, you have to clone the repository.

**Comment by keimlink** [comment]
Sorry! I thought this was an API client.

**Comment by martincarrera** [comment]
Hey, I will create a npm module to consume this API soon.

I'll just keep this issue updated when I do it.

**Comment by martincarrera** [comment]
It's not 100% ready yet (I still didn't create enough tests and have a couple of minor things to fix), but you can already use it.

[NPM module](https://www.npmjs.com/package/clashapi)
