### ISSUE TITLE
Update API

### ISSUE THREAD

**Issue by martincarrera** [martincarrera/clash-royale-api#27]
The API should have all the new chests and cards available in the September 19th update.

**Comment by hiimivantang** [comment]
agree

**Comment by martincarrera** [comment]
Mega minion and Inferno dragon added.

**Comment by matthewting** [comment]
If somewhat you can get an api to search open public tournment, that will be super.. lol thanks for the effort!

**Comment by amirm3hdi** [comment]
@martincarrera Why the graveyard is 404?
http://www.clashapi.xyz/images/cards/graveyard.png

**Comment by martincarrera** [comment]
The API is out to date. I will update it later today. I will let you know when updated. Thanks for your comment @amirm3hdi!

**Comment by amirm3hdi** [comment]
@martincarrera Also the **Inferno Dragon**'s image has no padding around it:
http://www.clashapi.xyz/images/cards/inferno-dragon.png

**Comment by amirm3hdi** [comment]
Wow, I just checked couple of other images, many of the card images have different padding... WTF :laughing: 
Please fix it.

**Comment by amirm3hdi** [comment]
I've found some images without any spaces all good!
Check graveyard out: http://clashroyale.news/img/cards/g/55.png
Here's the whole web: http://clashroyale.news/random-deck/arena-5.php

**Comment by amirm3hdi** [comment]
Also, rages spell elixir cost is outdated.

**Comment by martincarrera** [comment]
Hi guys, 

First of all, thanks to all for your comments.

I'll update all the wrong information soon, sorry for the delay!

**Comment by martincarrera** [comment]
API updated! 

New cards, chests, and images added.
