### ISSUE TITLE
how works this api?

### ISSUE THREAD

**Issue by iZume** [martincarrera/clash-royale-api#29]
what is the mechanism? where is data which get the script?

**Comment by gillchristian** [comment]
Hi @iZume, thanks for asking.

This is a RESTfull API. It is running at [`www.clashapi.xyz`](http://www.clashapi.xyz/). So you don't nee to run it yourself, just consume it.

All the routes are documented on the [`README`](https://github.com/martincarrera/clash-royale-api#how-to-use).

**Comment by martincarrera** [comment]
Hi @iZume, as @gillchristian told you, it's not necessary for you to host the API, you can just consume it from [Clashapi](www.clashapi.xyz).

However, you can download the code and host it anywhere, but in that case you will need to manually upload all the information.

Thanks for writing!
