### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by dwoloszin** [martincarrera/clash-royale-api#35]
hi,
could you post some tutorial about to use this Api since the beginning? I'm having some trouble to use this api.
tks a lot!

**Comment by martincarrera** [comment]
Hi!

I don't see the point of writing a tutorial right now, but if you let me know what troubles you are having, I can help you and then make the documentation so nobody else finds the same problems.

Let me know how I can help you!

Thanks!

**Comment by amirm3hdi** [comment]
@dwoloszin You need to select an API route that you need and extract the data with a `GET` method and the rest is json handling.
What language are you using? I can provide you an example.

**Comment by martincarrera** [comment]
Hi, I'm closing this issue. If you have any specific question about the API, please feel free to reopen this issue or create a new one. Thanks!
