### ISSUE TITLE
Incorrect elixir cost for Goblin Barrel (Should be 3 not 4)

### ISSUE THREAD

**Issue by amirm3hdi** [martincarrera/clash-royale-api#36]
Someone reported this at my website:

![image](https://cloud.githubusercontent.com/assets/4629328/23327229/e55f6e2e-fb21-11e6-890b-f2f578182b03.png)

**Comment by martincarrera** [comment]
Fixed! Thanks you!

<img width="600" alt="captura de pantalla 2017-02-25 a las 1 59 54 a m" src="https://cloud.githubusercontent.com/assets/6719062/23328368/3cfea38a-fafe-11e6-9b7f-309619337da8.png">

**Comment by amirm3hdi** [comment]
Nice screenshot lol
