### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by abinabinabin** [martincarrera/clash-royale-api#38]
hi.
I have a question

1. Can you use it in Unity?
If you can use it, please guide me

2. Do you have a win / lose API?

Thanks

**Comment by martincarrera** [comment]
Hi!

I don't have any experience with Unity, but I am pretty sure you can, you just have to send a GET request to the endpoints you need.

I'm sorry but I don't have a win/lose API, as I am not able to get information of the current game, just I show the static information that you just can _copy & paste_ from the game.

Let me know if I can help you with anything else! And thanks for using my API!

**Comment by abinabinabin** [comment]
Thanks for the reply!

Static information What is it?
Please explain

I will study the GET request method.

**Comment by martincarrera** [comment]
Is all the information like cards names, description, elixir costs, arenas, etc.

I am not able to get any information like player cards level, gold, gems, experience, win/lost battles, etc.

**Comment by abinabinabin** [comment]
All right! I understand
Thank you so much!

**Comment by martincarrera** [comment]
You are welcome! I will close this issue now, if you have any other question, feel free to create a new issue.

Thanks!
