### ISSUE TITLE
Can clash api get player match/top players info ? 

### ISSUE THREAD

**Issue by zhengli6** [martincarrera/clash-royale-api#39]
Hi,

This is a great api to be used for clash royale. Thank you for your efforts, I am thinking using some match data inside clash royale to doing some interesting projects. I am wondering is this api able to acquire top players gameTag as well as their recent match records and decks they are using?  

Thanks

**Comment by martincarrera** [comment]
Hi @zhengli6!

I'm sorry but I am not able to get any information about the battles, or a players cards level, or any information about the decks that current users are using, as there is no official API.

I just provide the general information about the chests, cards, arenas, and player leves (experience, tower hitpoints, etc.) but while there is no official API, I will not be able to provide current game information.

If you finally use my API, please let me know and submit a pull request with the app you developed so I can add it to the `README.md`.

Thanks!

**Comment by zhengli6** [comment]
Martincarrera, 

Thanks for quick reply, I guess the player match records would be useful if can be pulled via api. I found this website that provides real-time top 1000 players and their recent match records.  But I have no clue how they manage to obtain such data. 

Here is the website I found: 
https://statsroyale.com/top/players

Maybe you can figure it out.

**Comment by martincarrera** [comment]
I am not able to think how it is done, at least in a "legal" way. 

I'm sorry but as long as SuperCell don't create an official API, I will not be able to provide such information.
