### ISSUE TITLE
Update API

### ISSUE THREAD

**Issue by martincarrera** [martincarrera/clash-royale-api#42]
Update API to include the changes made with the March update.

**Comment by MaherFa** [comment]
I have recompiled the game textures and have the latest card art, they're high quality border-less and without the elixir drop atm, I can provide them as they are or add borders and give you them as PNGs, are you interested?

**Comment by martincarrera** [comment]
Of course! If you can, add the border, update the images in the `images` folder and submit a pull request. Thanks!

**Comment by MaherFa** [comment]
Do you care for the rarity glow (golden for rares and pink for epics)? like do you consider it a feature or is it not needed.
and what about the elixer drop?
atm I have all PNGs ready with borders and without the glow nor the elixir drop. imo I think they look cleaner like this but it's up to you.

also wanted to double check with you about the "idName" (image names) for the new cards, I used:
- bandit
- night-witch
- bats
- heal

**Comment by martincarrera** [comment]
It is OK without the glow and the elixir drops, I am not sure how much effort should mean adding the glow and how it would look like. If you want, submit a pull request as you have it now and if you want to add the glow and submit a new pull request in the future, it's up to you.

The names are OK like that, thanks!

**Comment by MaherFa** [comment]
effort is not an issue, I want this to be perfect. the issue is about consistency... old images only had glow for rares and epics and mostly because they were taken from screenshots. 
if we want to add glow we would have to add transparent pixels to cards without glow (commons and legendaries) to preserve the unity of image sizes.

anyway I uploaded the files for now but rather work on the arenas. I also have them clean with pixel perfect edges including the new legendary arena. 

most likely work on them tomorrow  along with the new double-chest and the new league Icons

**Comment by martincarrera** [comment]
Update: @MaherFa [here](https://github.com/martincarrera/clash-royale-api-data-generator/blob/master/data/cards.json) is the json of updated cards. As soon as I add the new chests and leagues information, it will be in production.

**Comment by MaherFa** [comment]
Thank you so much. I will work on chest images and submit them later. Do you prefer them opened or closed. I will be creating them out of the original mutipart animation sprites. So I can create whatever frame we want. Any preferance?

**Comment by martincarrera** [comment]
You are the expert here, just see which one looks better and go ahead with that one.

Thanks again for all your time!

**Comment by martincarrera** [comment]
API is now up to date. @MaherFa I will create a issue for you to update the chests images, is it OK?

**Comment by MaherFa** [comment]
No need, chests are ready
