### ISSUE TITLE
Arenas and Leagues

### ISSUE THREAD

**Issue by MaherFa** [martincarrera/clash-royale-api#44]
I'm about to submit a pull request for the new arena images but I need to know a couple of things.

1. shouldn't we avoid using the single quote `'` character in the `idName` of `pekka's-playhouse` and `builder's-workshop`
2. are you planing to add the new "Leagues" to the arenas or do you want to create a new route for them? 

## Available Arenas
barbarian-bowl
bone-pit
builder's-workshop
frozen-peak
goblin-stadium
hog-mountain
jungle-arena
legendary-arena
pekka's-playhouse
royal-arena
spell-valley
training-camp

## Available Leagues
blank
challenger-ii
challenger-iii
champion
chellenger-i
grand-champion
master-i
master-ii
master-iii
ultimate-champion

**Comment by martincarrera** [comment]
Hi!

Right now, let's just keep using the `'` character, but I'll take it into consideration in the next update.

For the leagues, I haven't thought which is the best way to implement it, please add the images in a different folder named `Leagues`, as I think I will implement a new endpoint for the leagues.

Thanks again for all your work!

**Comment by MaherFa** [comment]
Done, sorry about the duplicate "card images" pull request, couldn't sync fork :/ 

I'll try to figure it out before next commit. 


did you get the new card info yet? 
I need an updated `api/cards` JSON (offline will do) for something I'm working on

**Comment by MaherFa** [comment]
Done, https://github.com/martincarrera/clash-royale-api/pull/47

Arenas were updated and I added the `leagues` folder too.

**Comment by martincarrera** [comment]
Thanks for all your work! It´s amazing!
