### ISSUE TITLE
Minions Card Issue

### ISSUE THREAD

**Issue by barreeeiroo** [martincarrera/clash-royale-api#46]
The minions card doesn't have an order:
![image](https://cloud.githubusercontent.com/assets/19251112/24072237/54e31e6c-0be4-11e7-9a3f-eb90ebcb16fb.png)
I'm creating a bot for Telegram using your amazing API (congrats for making so cool), but as you can see there is no order in the JSON response:
`{"_id":"58976166fa5bce0010123fb2","idName":"minions","rarity":"Common","type":"Troop","name":"Minions","description":"Three fast, unarmored flying attackers. Roses are red, minions are blue, they can fly, and will crush you!","arena":2,"elixirCost":3,"__v":0}`

Could you fix it?
Thanks

**Comment by martincarrera** [comment]
Of course! Thanks for letting me know!

I will fix it later today, and add the new cards to the API.

I´ll let you know when it´s done.

**Comment by martincarrera** [comment]
Sorry for the delay. It should be fixed now.

Please let me know if you find something else.

Thanks!
