### ISSUE TITLE
League Name Error

### ISSUE THREAD

**Issue by barreeeiroo** [martincarrera/clash-royale-api#48]
There is a little error name in the Challenger 1 league: The image is called chellenger-i.png instead of challenger-i.png

https://github.com/martincarrera/clash-royale-api/blob/master/public/images/leagues/chellenger-i.png
https://github.com/martincarrera/clash-royale-api/blob/master/public/images/leagues/challenger-i.png

**Comment by martincarrera** [comment]
Thanks for creating this issue. Can you fix it and submit a pull request? If not, I can fix it later today.

Thanks!

**Comment by martincarrera** [comment]
Fixed by @MaherFa in #49
