### ISSUE TITLE
Bad codeship badge 404

### ISSUE THREAD

**Issue by amirm3hdi** [martincarrera/clash-royale-api#50]
The image from readme is 404 https://app.codeship.com/projects/153028.

![image](https://cloud.githubusercontent.com/assets/4629328/24144110/788e6b24-0e45-11e7-8226-3ce9267cb4b1.png)

**Comment by martincarrera** [comment]
Hi! I see it OK. Maybe it took a little longer to upload?

<img width="924" alt="captura de pantalla 2017-03-21 a las 9 16 11 a m" src="https://cloud.githubusercontent.com/assets/6719062/24146992/ffaa91a2-0e16-11e7-9604-fbdaee6db0fa.png">

**Comment by amirm3hdi** [comment]
@martincarrera I thought that too, Refreshed a couple of times, went to the URL and it was Application Error, anyway it is not 404 or application error anymore.
