### ISSUE TITLE
Level Image

### ISSUE THREAD

**Issue by barreeeiroo** [martincarrera/clash-royale-api#59]
Will be possible to add the level image to the API? I mean, to add the blue star with the level

**Comment by MaherFa** [comment]
I'll be adding stat icons soon, I'll add the elixir drop and level star and some more useful icons

**Comment by AmirSavand** [comment]
@MaherFa @barreeeiroo @martincarrera OT: The 2v2 update is killing it, so fun :D

**Comment by MaherFa** [comment]
done (https://github.com/martincarrera/clash-royale-api/pull/75/commits/1d27efaf2e9da731cb3cc69016df433bf063d8b8)
