### ISSUE TITLE
Adding stat icons

### ISSUE THREAD

**Issue by MaherFa** [martincarrera/clash-royale-api#73]
I now have high quality versions of all stat icons and other UI elements of the game, including level star (https://github.com/martincarrera/clash-royale-api/issues/59) and other useful graphics.

I will be uploading them and adding a pull request but we need to agree on where to upload them.we can create a folder called `icons` or `misc` and upload them all in there or create a dir called `stats` for stat icons alone. and other icons to another directory.

opinions?

**Comment by martincarrera** [comment]
Hey! I think that we should create a folder with `levels` for the level stars, a `stats` folder for the stats icons and then if there are other UI elements, maybe a `misc` folder. But trying to always group the items in a separated folder if possible.

Thanks again @MaherFa!

**Comment by MaherFa** [comment]
I ended up putting stat icons in `stats` and the rest in `ui`, I'll be uploading ui graphics soon

**Comment by MaherFa** [comment]
Final pull (https://github.com/martincarrera/clash-royale-api/pull/75/commits/1d27efaf2e9da731cb3cc69016df433bf063d8b8)

**Comment by martincarrera** [comment]
Closed by #75.
