### ISSUE TITLE
Add Card Image

### ISSUE THREAD

**Issue by yshahin** [martincarrera/clash-royale-api#77]
I makes sense to have the character card images here as well

**Comment by MaherFa** [comment]
We already have them under `public/images/cards` and can also be grabbed using the instructions on `readme.md`.
Is this what you're for?

**Comment by yshahin** [comment]
Why aren't they returned in the Json response of the API?
Shouldn't there be an imageUrl property in the card info?

**Comment by MaherFa** [comment]
There's a property called `idName` that holds the name of the image. And the rest of the url is static. So you can use our host or any other host you want

**Comment by yshahin** [comment]
Great thanks

**Comment by martincarrera** [comment]
Thanks @MaherFa for clearing this up. I'm closing this issue, @yshahin if you have any other question, don't hesitate to create a new one.
