### ISSUE TITLE
Clans

### ISSUE THREAD

**Issue by NathanNr** [martincarrera/clash-royale-api#80]
How can I get information about a specified clan or player?

**Comment by MaherFa** [comment]
You can't, Supercell doesn't provide any access to the ladder, player nor clans information. Everything found here is collected manually. And that can't be done with players and clans.

Unless SC provide us with an official api or with release player and clan stats somewhere this can't be done at all.

**Comment by martincarrera** [comment]
I'm sorry, but as @MaherFa said, as long as SuperCell doesn't provide an official API, we are not able to have that information.

**Comment by NathanNr** [comment]
Okay, thank you for your answer.

**Comment by barreeeiroo** [comment]
Maybe SuperCell could add it as ClashOfClans has it

SuperCell released an API for ClashOfClans:
developer.clashofclans.com

**Comment by Ruudt** [comment]
How do starfi.re and statsroyale.com get their information? Has something changed?

**Comment by martincarrera** [comment]
I have no clue, to be honest. But I'm pretty sure that it's not very legal.

**Comment by Ruudt** [comment]
I would like to find out because it seems that statsroyale.com falls within the (Supercell fan content policy)[http://supercell.com/en/fan-content-policy/] and starfi.re is a (featured fansite by Clash Royale)[mobile.twitter.com/ClashRoyale/status/851807938943614977].
