### ISSUE TITLE
Check out this new clash royale api... 

### ISSUE THREAD

**Issue by atulya2109** [martincarrera/clash-royale-api#86]
[Stats-Royale-Python](https://github.com/atulya2109/Stats-Royale-Python/) This api scrapes [StatsRoyale ](https://www.statsroyale.com) to get player details, upcoming chests in chest cycle, last few battles from player tag clan members and clan details from clan tag.

The only main problem is that the scraper breaks down when the HTML  of the website is changed. 
It would be great to have a few helping hands.

**Comment by martincarrera** [comment]
Hey! It looks great. However, I am really busy so I am not able to dedicate a lot of time to open source projects 😢 

I will try to keep my API updated and with some improvements, but I won't be able to help in other projects. Sorry!
