### ISSUE TITLE
API Site seems down

### ISSUE THREAD

**Issue by guachitonico** [martincarrera/clash-royale-api#87]
I just tried browsing http://www.clashapi.xyz/ 
and I'm getting Application Error: An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

My app heavily relies upon the site, so I'd love the website back up as soon as possible.

**Comment by martincarrera** [comment]
Seems up from here, maybe it was down a little period of time.

Anyway, I've been really busy this last few months but I'm working on some upgrades on this app so it is 100% up.
