### ISSUE TITLE
Add new cards

### ISSUE THREAD

**Issue by guachitonico** [martincarrera/clash-royale-api#88]
Hi,
I checked you have an already built utility to easily add cards to the server.
Will you add the latest CR cards?
Cannon Cart - Epic, 5 elixir, Troop, Arena Hog Mountain, Ground unit
Flying Machine - Rare, 4 elixir, Troop, Jungle Arena, Air unit
Mega Knight - Legendary, 7 elixir, troop, hog mountain, ground unit

Thanks!

**Comment by martincarrera** [comment]
Sure, sorry for the delay adding this cards. I will do in a couple hours.

**Comment by guachitonico** [comment]
Thanks!

**Comment by martincarrera** [comment]
Cards added!
