### ISSUE TITLE
Add missing cards images

### ISSUE THREAD

**Issue by martincarrera** [martincarrera/clash-royale-api#89]
* Cannon Cart (`cannon-cart.png`)
* Mega Knight (`mega-knight.png`)
* Flying Machine (`flying-machine.png`)

@MaherFa @AmirSavand it's been a while, could you help me out with this? Thanks!

**Comment by MaherFa** [comment]
been too busy lately, I'm on it

**Comment by martincarrera** [comment]
Thanks! 🎉
