### ISSUE TITLE
How do you get this to work?

### ISSUE THREAD

**Issue by MikeOntry** [martincarrera/clash-royale-api#9]
I've got your files in a directory on my computer. I've installed node.js. I imported the dependencies with `npm install`. When I try to start it up with `npm start` I get this error:

```
\server.js:242
       process.nextTick(function() { throw err; })
                                     ^
Error: connect ECONNREFUSED 127.0.0.1:27017
   at Object.exports._errnoException (util.js:870:11)
   at exports._exceptionWithHostPort (util.js:893:20)
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1061:14)
```

I'm a very very new to node.js and Mongo. I only started really looking at them because of this. Help please! :+1:

**Comment by MikeOntry** [comment]
OK. I figured out I have to install MongoDB also. I can now go to `localhost:8085` and see

```
{
"message": "Welcome to Clash Royale API!"
}
```

Now I just need to figure how to actually get data from it.

**Comment by martincarrera** [comment]
It´s currently under development, so it does not have any data and there is no documentation.

You could upload data via POST to each of the routes (cards, chests, players or arenas).

If you are not familiar with REST APIs, I recommend you to read this. [Teach a dog to REST](http://es.slideshare.net/landlessness/teach-a-dog-to-rest)

As soon as I finish this I will write more docs and create all the data so you can just request it and use it.

I will close this issue, if you have any questions, feel free to write an email to this address: mcarrera.92@gmail.com
