### ISSUE TITLE
can i use these emojis for my app ?

### ISSUE THREAD

**Issue by PlayableApps** [martincarrera/clash-royale-api#90]
hello Mr. Martin Carrera 

i just want to know if i can use these funny emojis for my own app ?

is that legal ?

**Comment by martincarrera** [comment]
Hey! If you ask me, I don't mind if you use them.

Just be sure you don't break any term and condition from SuperCell.

When you finish your app, if you use my API, please submit a pull request with info about it, and please tell me so I can try it!

😄

**Comment by PlayableApps** [comment]
Hey Mr. Martin Carrera! thank you for the nice Reply!
I'm actually a very Beginner! the game i'm making is just a tic tac toe
Haha!
but for fun i added those amazing emojis , i really don't know if that
breaks any term and condition from SuperCell ?
these copyrights issues SCARES ME man. so i'm trying to play safe :)

thanks again sir and have a nice day!😊
