### ISSUE TITLE
get example 

### ISSUE THREAD

**Issue by hanscees** [martincarrera/clash-royale-api#91]
hi, I do not understand how to make a succesful api call

This does not work
http://www.clashapi.xyz/api/cards/:arrows

it says "wrong id, object nog found. I have tried a number of other ways. 

What is the right way to do this?

**Comment by martincarrera** [comment]
Without the `:`

http://www.clashapi.xyz/api/cards/arrows

**Comment by martincarrera** [comment]
I'm closing this issue, if you have any other question please don't hesitate to ask.
