### ISSUE TITLE
Add card id

### ISSUE THREAD

**Issue by lluisd** [martincarrera/clash-royale-api#92]
Hi,

Can we add the card ids? like https://docs.google.com/spreadsheets/d/1hvoz1vYbK5-Wine0oRnmrZvkSRVK5ezr2VJbwUog2io/edit#gid=0 to share decks.

**Comment by martincarrera** [comment]
Hi!

If you could confirm the new cards ids I'll try to add them.

Thanks!

**Comment by TorzuoliH** [comment]
Hi @martincarrera!

I can add new card ids. Where would you like to place them?

**Comment by MaherFa** [comment]
I support this, @AmirSavand have obtained a complete list from Reddit, see here (https://github.com/martincarrera/clash-royale-api/issues/109)

**Comment by martincarrera** [comment]
I will try to add the card ids this week, I'm currently super busy right now, so if you like you can add it on each card in the data generator as `copyId` and I'll update the API to support it, that way you could help A LOT!

**Comment by TorzuoliH** [comment]
@AmirSavand @MaherFa If some of you starts the job, please tell us here. Don't do duplicate work!

**Comment by martincarrera** [comment]
Added `copyId` on each card.

If you see a wrong id please let me know as soon as possible.
