### ISSUE TITLE
Improve images

### ISSUE THREAD

**Issue by martincarrera** [martincarrera/clash-royale-api#95]
I added the new images but those look really poor.

@MaherFa @AmirSavand could you help me out with this?

* Arena:
  * `electro-valley.png`

* Cards:
  * `hunter.png`
  * `royal-ghost.png`
  * `zappies.png`

* Chests:
  * `fortune-chest.png`
  * `kings-chest.png`
  * `legendary-kings-chest.png`
  * `lightning-chest.png`

**Comment by MaherFa** [comment]
I'd love to help, but recently SC implemented a new way of storing data, they basically download images and store them in `\data\` instead of packing them inside the apk (the way I used to unpack and decode them).

I'm yet to find a way to get those so we may have to wait for the apk file update.

**Comment by AmirSavand** [comment]
+1

**Comment by MaherFa** [comment]
Done! thx to @Galaxy1036 python script
